### ISSUE TITLE
Publish to flutter registry?

### ISSUE THREAD

**Issue by gdpelican** [NourEldinShobier/carbon-flutter#1]
Hello, it says in the README that this is the start of a Dart package to publish to the flutter registry; what needs to be done in order to make this available there?

**Comment by NourEldinShobier** [comment]
@gdpelican Hi, sorry for the late reply I was busy with my studies. The project is still under development. I will continue adding more components once I finish  this semester.

what I finished so far:

1. Buttons: Primary, Secondary, Ghost, Danger, Tertiary
2. TextField: Primary, Warning, Error
3. Checkbox
4. Table
