### ISSUE TITLE
Some screenshot examples to demonstrate the look and feel in readme

### ISSUE THREAD

**Issue by peterpoliwoda** [NourEldinShobier/carbon-flutter#2]
Hi @NourEldinShobier could you add some example screenshot to your Readme file to demonstrate how this looks, please?
Btw, brilliant that you took the time to put this together. Thank you!

**Comment by NourEldinShobier** [comment]
Hi @peterpoliwoda I'll try to add screenshots of the finished widgets today, and later on I will add some documentation of how the widgets works
